version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    