services:
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app:consistent #DO :consistent WHILE DEVELOPING. DO :delegated WHEN DEPLOYING APP.
      - /app/__pycache__  #Avoid syncing cache files
      - /app/.venv  #Ignore virtual env if using one
    ports:
      - "8000:8000"
    networks:
      - my-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - my-network

networks:
  my-network:
    